--
--Definintion Prop Base On Script
--
PROMPT_KIND_NORMAL      = 0
PROMPT_KIND_ERROR       = 1

NOTE_TYPE_DEBUG         = 0
NOTE_TYPE_NORMAL        = 1
NOTE_TYPE_TRIVIAL       = 2
NOTE_TYPE_NORMAL_RED    = 3
NOTE_TYPE_TRIVIAL_RED   = 4
NOTE_TYPE_TOP           = 5
NOTE_TYPE_NORMAL_WHITE  = 6
NOTE_TYPE_TRIVIAL_WHITE = 12

COMBAT_PROP_CLASS_DATA  = 1
COMBAT_PROP_CLASS_MIN   = 2
COMBAT_PROP_CLASS_MAX   = 3


THINGS_MAX                       = 2100000000
COIN_MAX                         = 9999999999

--------------------------------------------通用接口1---------------------------------------
FUNC_TEST                        = 0   --TEST
FUNC_TEAM_CALL                   = 1   --队伍集结
FUNC_UPDATE_PLAYER_PROP          = 2   --更新角色属性
FUNC_ITEM_USE                    = 3   --物品使用
FUNC_PLAYER_RELIVE               = 4   --人物复活
FUNC_KICK_FROM_GUILD             = 5   --被踢出行会
FUNC_GIFT_REWARD                 = 6   --离线奖励礼包
FUNC_UPDATE_PLAYER_EVENT         = 7   --更新角色事件
FUNC_FIND_BACK_ITEM              = 8   --物品找回
FUNC_GUILD_CALL                  = 9   --行会召集
FUNC_RECHARGE_ONCE               = 10  -- 单笔充值礼包
FUNC_CAI_SHEN_LAN_LU             = 11  -- 财神拦路
FUNC_BOOTH_NOTE                  = 12  -- 摆摊日志
FUNC_OFFLINE_EXP                 = 13  -- 离线经验
FUNC_CHANGE_ITEM                 = 16  -- 物品兑换
FUNC_MAIL_DATA                   = 17  -- 邮件
FUNC_SET_ATTACK_MODE             = 18  -- 设置攻击模式
FUNC_RENAME                      = 20  -- 改名字
FUNC_GET_YK                      = 22  --获得月卡
FUNC_GET_OPEN_WARE_HOUSE         = 23  --开背包
FUNC_GET_FULL_PACKAGE            = 24  --下完整包
FUNC_FORGE                       = 25  --锻造
FUNC_OFFLINE_SID                 = 28  --切换离线场景id
FUNC_FLY_PRIVATE_DART            = 29  --传送到个人镖车附近
FUNC_CANCEL_GATHER               = 31  --取消采集
FUNC_OPPO                        = 34  --OPPO专属活动
FUNC_QUIT_HUICHENG               = 38  --回城
FUNC_JOIN_ACTIVITYY              = 39  --参加日常活动
FUNC_GUILD_CANTEEN               = 40  --公会食堂
FUNC_JBP_MONEY                   = 41  --聚宝盆
FUNC_ZBG_BUYITEM                 = 42  --珍宝阁买东西
FUNC_ZBG_SETDISCOUNT             = 43  --珍宝阁打折
FUNC_ZBG_FRESHITEM               = 44  --珍宝阁刷新
FUNC_GUILD_BATTLE                = 45  --行会对战
FUNC_MERGE_GUILD                 = 46  --邀请行会
FUNC_ADD_GUILD_TO_SDK            = 47  --加入行会上报sdk
FUNC_INVERST_BUY                 = 54  --投资
FUNC_INVERST_GETAWARD            = 55  --投资 领取奖励
FUNC_HC_JYD_REQUEST              = 56  --请求合成经验丹
FUNC_GODWEAPON_GIFT_BUY          = 57  --购买神器礼包
FUNC_GET_VIP_TASK_AWARD          = 60  --获取VIP尊享任务奖励
FUNC_FIGHT_CSZT                  = 61  --传说之塔挑战
FUNC_BUY_FOGE_POWER              = 63  --购买狂暴之力请求
FUNC_SETTINF_FETCH_MAIN          = 64  --拾取大类设置
FUNC_CAREER_STUFF                = 66  --打金之路 职业生涯
FUNC_FIRE_RAIN                   = 67  --火雨礼包
FUNC_QUIT_HUICHENG_OR_SUJI       = 68  --回城或随机（按血值比例触发）
FUNC_MAIN_QUEST_STUFF            = 69  --主线任务
FUNC_SWZDZ                       = 70  --尸王争夺战
FUNC_CANGLONG_GIFT               = 71  --苍龙礼包
FUNC_MENGCHONG_GIFT              = 72  --萌宠礼包
FUNC_FETCH_ITEM                  = 73  --物品
FUNC_ENTER_MOLING_MAP            = 74  --进入魔灵地图
AUTO_USE_JYD_CIPS                = 75  --自动使用经验丹
FUNC_SERVER_PLAYER_STATE         = 77  -- 服务器玩家状态
FUNC_CHALLENGE_MAFA_HISTORY      = 78  -- 挑战玛法史诗
FUNC_TUOGUAN                     = 80  -- 托管
FUN_ONBUY_EXP                    = 81  -- 购买战令经验
FUN_ONGET_EXP                    = 82  -- 领取战令经验
FUN_ONGET_REWARD                 = 83  -- 领取战令奖励
FUNC_GONGLUE_READ_STATE          = 86  -- 攻略是否已读
FUNC_GET_GONGLUE_AWARD           = 87  -- 领取攻略奖励
FUNC_WORLD_BOSS                  = 88  -- 世界boss
FUNC_GUILD_QUEST                 = 89  -- 特殊任务
FUNC_SKILL_RED_POINT_MODE        = 90  -- 技能红点模式
FUNC_GET_YFCT_REWARD             = 91  -- 获得一飞冲天奖励
FUNC_COMPOUND                    = 92  -- 合成道具
FUNC_WEEK_CARD_MARKET            = 93  -- 推送周卡
FUNC_LINGWEN                     = 94  -- 灵纹
FUNC_GET_FPZN_AWARD              = 95  -- 领取防骗指南奖励
FUNC_GET_ZK_REWARD               = 96  -- 获得周卡奖励
FUNC_GO_BLACK_MARKET_MAP         = 103 -- 前往黑市商人地图
FUNC_ASK_BLACK_MARKET            = 104 -- 打听黑市商人任务
FUNC_READ_GMD_NOTIFY             = 106 -- 已读光明顶通知
FUNC_SET_BOSS_DIFFICULTY         = 114 -- 设置个人BOSS难度
FUNC_QUEST_EQUIP                 = 117 -- 主线任务装备洗练和装备重铸 83，84
FUNC_BUY_SPONSOR                 = 119 -- 购买赞助
FUNC_YABIAO_ONCE                 = 121 -- 一键押镖
FUNC_FIND_SHENBING               = 122 -- 找回神兵
FUNC_QUEST_SIDE_GET_REWARDS      = 123 -- 领取支线任务奖励
FUNC_SEEN_WEIXIN                 = 124 -- 看过微信福利
FUNC_RONGHE_JINJIE               = 125 -- 融合进阶
FUNC_RONGLIAN                    = 126 -- 熔炼
FUNC_BAOSHI_PUT_ON               = 128 -- 宝石镶嵌
FUNC_BAOSHI_PUT_OFF              = 129 -- 宝石卸下
FUNC_BAOWU_LEVELUP               = 130 -- 宝物升级
FUNC_NTGM_LEVELUP                = 131 -- 逆天改命升级
FUNC_SETTING_PICK                = 132 -- 拾取
FUNC_KFHD_GUILD                  = 133 -- 行会赞助
FUNC_KFHD_DROP                   = 134 -- 首爆
FUNC_KFHD_DROP_TIPS              = 135 -- 首爆提示
FUNC_SHENBING_HC                 = 136 -- 神兵合成 升级
FUNC_GET_VIP_FREE_GIFT           = 137 -- vip免费礼物领取
FUNC_PAY_VIP_PAY_GIFT            = 138 -- vip购买付费礼物
FUNC_BAG_FULL_PROP               = 139 -- 背包第一次满引导
FUNC_DIVINE_HOLY                 = 141 -- 神圣剑甲升级
FUNC_XUEYUAN_BAOKU               = 142 -- 学院宝库
FUNC_CORNUCOPIA                  = 143 -- 聚宝盆
FUNC_XJP_COMPOSE                 = 146 -- 小极品合成
FUNC_GUARD_UPGRADE               = 147 -- 守护升级
FUNC_SC_DONATE                   = 148 -- 沙城捐献
FUNC_EQUIP_ENHANCE               = 149 -- 强化
FUNC_HERALDRY                    = 150 -- 纹章升级
FUNC_BOSS_RELIVE                 = 151 -- Boss复活
FUNC_REINCARNATION               = 152 -- 转生及炼体
FUNC_MOWEN                       = 153 -- 魔纹融合拆分
FUNC_DRESS                       = 154 -- 装扮
FUNC_SUBMIT_BRANCH_TASK          = 155 -- 提交支线任务
FUNC_COMPLETE_LOOK_FURY          = 156 -- 了解狂暴任务
FUNC_GCZ                         = 157 -- 攻城战
FUNC_SHFB_REWARD                 = 158 -- 领取守护副本奖励
FUNC_SX_HC                       = 159 -- 生肖装备合成
FUNC_YZBQ                        = 160 -- 夜战比奇城
FUNC_RED_RECOVERY                = 161 -- 红包道具回收
FUNC_RESET_EVENT                 = 162 -- 客户端通知服务器重置事件
FUNC_FIRSTBLOOD_REWARD           = 163 -- 首杀奖励
FUNC_FIND_TREASURE               = 165 -- 寻宝
FUNC_BUY_GUILD_BUFF              = 169 -- 购买帮会强化BUFF
FUNC_BUY_GUILD_TOKEN_UPGRADE     = 170 -- 工会令牌升级
FUNC_GET_FULI_REWARDS            = 171 -- 领取福利投资奖励
FUNC_BUY_FULI_TOUZI              = 172 -- 灵符购买福利投资
FUNC_GET_TURNTABLE_TASK          = 173 -- 转盘次数
FUNC_FULI_TURNTABLE_REWARD       = 174 -- 领取转盘奖励
FUNC_HOLIDAY_JBP_OPEN            = 175 -- 打开聚宝盆
FUNC_HOLIDAY_JBP_PICK            = 176 -- 购买聚宝盆
FUNC_MONENY_TREE                 = 181 -- 摇钱树活动
FUNC_JJKH                        = 182 --竞技狂欢
FUNC_ZHUISHALING_CALL            = 183 --追杀令

FUNC_ON_GET_ITEM_SHOW            = 187 --获取道具展示
FUNC_JUMP_SCENE_POS              = 188 --跳转指定场景坐标
FUNC_GET_ACTIVITY_ALL_REWARDS    = 189 --一键购买所有礼包
FUNC_MLGJ                        = 190 --猛龙过江抽奖
FUNC_MLGJ_REPORT                 = 191 --猛龙过江全服极品记录

FUNC_EQUIP_INCREASE              = 192 --装备增幅
FUNC_EQUIP_INHERIT               = 193 --装备传承
FUNC_EQUIP_INCREASE_TICKET       = 194 --装备传承使用卷
FUNC_FABAO_UPGRADE               = 195 --法宝激活升级
FUNC_FABAO_PUT_ON_OFF            = 196 --法宝穿戴脱下
FUNC_SUPER_BOOS_REWARD           = 197 --超级BOSS奖励
FUNC_FIND_TREASURE_PROGRESS      = 198 --寻宝进度奖励
FUNC_MQ_CUILIAN                  = 199 --魔气淬炼
FUNC_PROTECT                     = 200 -- 装备投保
FUNC_DECLARE_WAR                 = 201 -- 行会宣战
FUNC_LINGBAO_UPGRADE             = 202 -- 灵宝激活升级
FUNC_LINGBAO_PUTON               = 203 -- 灵宝佩戴
FUNC_EQUIP_UP_STAR               = 204 -- 装备升星
FUNC_NTGM_UPLEVEL                = 205 -- 逆天改命激活升级
FUNC_YBHS                        = 206 -- 元宝回收
FUNC_XUNZHANG_UPLEVEL            = 207 -- 勋章激活升级
FUNC_XUNZHANG_QUEST              = 208 -- 勋章任务
FUNC_SHENQI_ZHUZAO               = 209 -- 神器铸造
FUNC_GRBOSS_REWARD               = 210 -- 个人BOSS奖励
FUNC_BOSS_LEVEL_UP               = 211 -- BOSS图鉴升级
FUNC_AUTO_USE_DRUG               = 212 -- 自动使用药品
FUNC_GET_BOSS_SCORE              = 213 -- 获取BOSS积分
FUNC_KUAFU_BOSS                  = 214 -- 跨服BOSS
FUNC_SKILL_LEVEL_UP              = 215 -- 技能升级
FUNC_HUANJING_GET_FREE_TIME      = 216 -- 领取幻境免费时间
FUNC_HUANJING_BUY_TIME           = 217 -- 购买幻境时间
FUNC_HUANJING_REFRESH            = 218 -- 幻境刷新
FUNC_HUANJING_DAILY_TASK_COMMIT  = 219 -- 幻境日常任务提交
--------------------------------------------通用接口2---------------------------------------
FUNC_COMMON_RESET_SKILL_POSITION = 1   -- 重置技能位
FUNC_COMMON_SET_SKILL_POSITION   = 2   -- 设置技能位
FUNC_TURNTABLE_START             = 3   -- 大转盘锁定奖励
FUNC_SET_AUTO_RECOVERY_HUOJI     = 4   -- 设置自动回收、火祭
FUNC_FULI_TURNTABLE_START        = 5   -- 福利转盘锁定奖励
FUNC_CHANGE_JOB                  = 6   -- 转职
FUNC_KF3V3_REGISTER              = 7   -- KF3V3 报名
FUNC_KF3V3_ENTER                 = 8   -- KF3V3 入场
FUNC_KF3V3_LEAVE                 = 9   -- KF3V3 离场
FUNC_KF3V3_COMPETITION_TIME      = 10  -- KF3V3 比赛已经开启多长时间
FUNC_KF3V3_DAY_STATE             = 11  -- KF3V3 比赛日状态

-------------------------------------------物品ID-------------------------------------------
SjStoneId                        = 80001 -- 随机石id
HcStoneId                        = 80003 -- 回城石id


------------------------------------------其他配置------------------------------------------
BuyStoneCnt = 50             -- 随机/回城石购买数量
StoneOpenLevel = 15          -- 随机/回城石开启等级
AddCoinLevel = 30            -- 发放金币等级
AddCoinCount = 100000        -- 发放金币数量
TJMailSendLevel = 40         -- 特戒邮件发送等级
TJMailItemId = 65232         -- 特戒邮件发送物品id
GuildBuffPrice = 50          -- 帮会增强buff消耗灵符
ConsignMentTax = 15          -- 寄售行税率
ChaseAndKillOpenLimit = 50   --地图追杀开启条件
Activity_SJLB_Price = 138888 --神技礼包一键购买价格
AutoRandomStoneExCDTime = 5  --自动使用随机石 额外cd时间 /s
