
#ifndef _MSG_CATEGORY_H_INCLUDED
#define _MSG_CATEGORY_H_INCLUDED

//消息分类
enum MsgCategory
{
	MSG_CATEGORY_AUTH				= 0,		//验证消息
	MSG_CATEGORY_LOGIN				= 1,		//登录消息
	MSG_CATEGORY_CONTROL			= 2,		//控制消息
	MSG_CATEGORY_ENTITY				= 3,
	MSG_CATEGORY_SCENE				= 4,
	MSG_CATEGORY_PLAYER				= 5,
	MSG_CATEGORY_ITEM				= 6,
	MSG_CATEGORY_QUEST				= 7,
	MSG_CATEGORY_DOWNLOAD			= 8,
	MSG_CATEGORY_GUILD				= 12,
	MSG_CATEGORY_PET				= 14,
	MSG_CATEGORY_SHOP				= 15,
	MSG_CATEGORY_TRADE				= 16,
	MSG_CATEGORY_TEAM				= 17,
	MSG_CATEGORY_EVENT				= 18,
	MSG_CATEGORY_WORLD				= 19,
	MSG_CATEGORY_RELATIONSHIP		= 20,
	MSG_CATEGORY_MAIL				= 21,
	MSG_CATEGORY_SYSINFO            = 23,
	MSG_CATEGORY_MARKET				= 24,
	MSG_CATEGORY_CONSIGNMENT		= 25,
	MSG_CATEGORY_HOLIDAY			= 26,
	MSG_CATEGORY_HERO				= 27,
	MSG_CATEGORY_TEST				= 50,
	MSG_CATEGORY_GM					= 51,
	MSG_CATEGORY_SERVER_LOGIC		= 52,		// 服务器内部消息
	MSG_CATEGORY_CENTER             = 53,       //中心管理服消息
	MSG_CATEGORY_WAR_ZONE_BROADCAST = 54,     //发给战区内所有客户端消息
	MSG_CATEGORY_CHAT               = 60,
	MSG_CATEGORY_HTTP               = 61,
	MSG_CATEGORY_ZHANDUI			= 62,
	MSG_CATEGORY_CLIENT_MAX			= 80,		//all client<-->server msg's category should small than MSG_CATEGORY_CLIENT_MAX

	MSG_CATEGORY_DBCENTER			= 81,		//中心服务器数据库消息
	MSG_CATEGORY_GS_TO_GS           = 82,

	MSG_CATEGORY_DB_AUTH			= 101,
	MSG_CATEGORY_DB_LOGIN			= 102,
	MSG_CATEGORY_DB_PLAYER			= 104,
	MSG_CATEGORY_DB_ITEM			= 105,
	MSG_CATEGORY_DB_QUEST			= 106,
	MSG_CATEGORY_DB_TEST			= 107,
	MSG_CATEGORY_DB_ARENA			= 108,
	MSG_CATEGORY_DB_CHART			= 109,
	MSG_CATEGORY_DB_ROBOT			= 110,
	MSG_CATEGORY_DB_GUILD			= 111,
	MSG_CATEGORY_DB_BUDOKAI			= 112,
	MSG_CATEGORY_DB_PET				= 113,
	MSG_CATEGORY_DB_WORLD			= 114,
	MSG_CATEGORY_DB_RELATIONSHIP	= 115,
	MSG_CATEGORY_DB_RECORDS			= 116,
	MSG_CATEGORY_DB_CROSS			= 117,
	MSG_CATEGORY_DB_MAIL			= 118,
	MSG_CATEGORY_DB_CONSIGNMENT		= 120,
	MSG_CATEGORY_DB_HOLIDAY			= 121,
	MSG_CATEGORY_DB_HERO			= 122,
	MSG_CATEGORY_DB_ZHANDUI			= 123,
	MSG_CATEGORY_DB_MAX				= 126,

	MSG_CATEGORY_CROSS				= 127,
	MSG_CATEGORY_RedPack            = 128,
	
};

#endif	// _MSG_CATEGORY_H_INCLUDED
