//
//Generated by lua
//2009-2012	(C) XianFeng Inc. Reserved
//

#ifndef _MSG_REGISTER_H_INCLUDED
#define _MSG_REGISTER_H_INCLUDED

class MsgRegister
{
public:
	MsgRegister();
};

#endif	//_MSG_REGISTER_H_INCLUDED
