//
//Generated by lua
//2009-2012	(C) XianFeng Inc. Reserved
//

#include "MsgRegister.h"
#include "common/MsgFactory.h"

<%
for _, filename in ipairs(files) do
	local incname = filename
	incname = incname:gsub(".lua", ".h")
%>
#include "<%=incname%>"
<%
end
%>
#include "MsgWrapper.h"

MsgRegister::MsgRegister()
{
	<%
	for _, msg in ipairs(messages_all) do
	%>
	g_msg_factory.registerMessage<<%=msg.name%>>();
	<%
	end
	%>
	g_msg_factory.registerMessage<MsgSceneWrapper>();
}
